### ISSUE TITLE
Document certificate key file handling

### ISSUE THREAD

**Issue by phil-d-wilson** [balena-io-playground/cloudBlock#31]
Currently users will need to copy their `pfx` file into the `/app/components/secrets` directory in their dockerfile. We need to explain this in the readme - or a separate documentation file.

**Comment by kb2ma** [comment]
Yes, I have updated my [cloudBlock-test repo](https://github.com/kb2ma/cloudBlock-test/tree/main/sensor) -- docker-compose and Dockerfile to accommodate this requirement.

**Comment by phil-d-wilson** [comment]
https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/#setup-key-vault-and-service-principal

**Comment by kb2ma** [comment]
Added instructions to cloud block reference page.
