### ISSUE TITLE
Add support for other architectures

### ISSUE THREAD

**Issue by phil-d-wilson** [balena-io-playground/cloudBlock#32]
Currently the dockerfile has amd64 specific lines:

```
RUN wget -q https://github.com/dapr/dapr/releases/download/v1.0.1/daprd_linux_amd64.tar.gz
RUN tar -zxvf daprd_linux_amd64.tar.gz
```

This should be replaced with a downloaded script to install the correct dapr runtime for each archtecture.

**Comment by phil-d-wilson** [comment]
Can also explore the dapr.io install script, rather than install the binaries manually:

```
wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
```

from here: https://docs.dapr.io/getting-started/install-dapr-cli/

**Comment by kb2ma** [comment]
I looked into the dapr install script. It downloads the CLI, which is unnecessary for production. The script also selects the architecture for download based on `uname -m`, which doesn't fit use with docker buildx cross builds. So, in #35 I just continue to download the daprd executable.

@phil-d-wilson, have I missed your intention?

**Comment by phil-d-wilson** [comment]
@kb2ma not at all - you've hit the nails on their heads. :)
